import './globals.css'

import type { Metadata } from "next";

import HeaderBar from '@/src/components/headerBar';

import Image from 'next/image';

export const metadata: Metadata = {
  title: "kiol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          {/* <Image src="/images/github.png" width={24} height={24} alt='test'></Image> */}
          <HeaderBar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
