import './globals.css'
import type { Metadata } from "next";
import HeaderBar from '@/src/components/headerBar';

export const metadata: Metadata = {
  title: "kiol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <HeaderBar />
        </header>
        <hr />
        <main>{children}</main>
      </body>
    </html>
  );
}
