import './globals.css'

import type { Metadata } from "next";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <Link href='/'>home</Link>
              </li>
              <li>
                <Link href='/'>home</Link>
              </li>
              <li>
                <Link href='/'>home</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
